name: lint-and-test
on:
  pull_request

jobs:
  lint-and-test:
    name: Run Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7

      - name: Run tests
        run: go test ./...
